### ISSUE TITLE
Outdated Images

### ISSUE THREAD

**Issue by clayEnkidu** [TheOdinProject/css-exercises#329] opened 2023-06-22 07:43 UTC
Complete the following REQUIRED checkboxes:
-   [+ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ +] The title of this issue follows the `Outdated Images- location of Images: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
## All the images for the desired outcomes in the css-exercises/foundations are outdated hence they aren't loading or visible to others. I request you to look into the following folders and upload the latest images for beginners like me. 

**2. The Locations of the images are :**
>>> foundations/01-css-methods/desired-outcome.png 
>>> foundations/02-class-id-selectors/desired-outcome.png
>>> foundations/03-grouping-selectors/desired-outcome.png
>>>  foundations/04-chaining-selectors/desired-outcome.png
>>> foundations/05-descendant-combinator/desired-outcome.png
>>> foundations/06-cascade-fix/desired-outcome.png

**Comment by CouchofTomato** [comment] 2023-06-22 14:36
Hey @clayEnkidu 

What do you mean they aren't visible?

**Comment by clayEnkidu** [comment] 2023-06-30 04:58
![odinss](https://github.com/TheOdinProject/css-exercises/assets/80405570/4125d52c-47a1-4e6b-a9ed-7f26055f433d)

Can't see the desired outcome here.

**Comment by CouchofTomato** [comment] 2023-06-30 09:45
Thanks @clayEnkidu

It works for me so I'm not sure what the issue is but I don't think it's with the image in the repo.

![image](https://github.com/TheOdinProject/css-exercises/assets/12649577/0e0b52f7-0d83-4681-804f-2c9504852286)

**Comment by CouchofTomato** [comment] 2023-06-30 09:53
Closing as no other reports of this and cannot replicate

**Closed by CouchofTomato** 2023-06-30 09:53 UTC
Labels: Type: Bug, Status: Needs Review
