### ISSUE TITLE
07-flex-layout-2/solution: weird sidebar

### ISSUE THREAD

**Issue by 17radf** [TheOdinProject/css-exercises#60] opened 2021-10-25 04:52 UTC
![image](https://user-images.githubusercontent.com/12584890/138636490-62640ead-e566-4de5-b3c0-a01c0213a290.png)
Is it supposed to be like this? 

Solution: add `flex: 1;` to the card container instead of sidebar.
This is the solution output: 
![image](https://user-images.githubusercontent.com/12584890/138636312-88aa4e1f-27cc-44c3-aaa0-5b95573427e8.png)

**Comment by thatblindgeye** [comment] 2021-12-04 16:24
@17radf  Can you ellaborate on this issue? Is the first screen shot what *you* see when running your own solution? If so, then it sounds like this is less an issue with the exercise and more that you haven't yet solved the exercise.

If you have already solved this and moved on, please let me know and I will close this. Otherwise if you haven't still solved it, it may be worth asking for help on our Discord.

**Comment by 17radf** [comment] 2021-12-05 05:00
The first screenshot is the solution this repository gave me and it is showing like that instead of the requested output, and the second screenshot is mine with my own solution too.

I don't know about others whether it works on their browser or they have an issue just like me. But, yea I already solved it and moved on.

**Comment by thatblindgeye** [comment] 2021-12-05 17:49
When I open `solution.html` in both Firefox and Chrome I see the expected output, so I'm not sure what may have occurred.

Since you've moved on and it doesn't seem like the issue is a widespread one, I will close this issue, but thank you for mentioning it to be looked into.

**Closed by thatblindgeye** 2021-12-05 17:49 UTC
