### ISSUE TITLE
Bug - : the desired outcome image and actual solution is very different  you  need to review it. Thanks.

### ISSUE THREAD

**Issue by Rahilya** [TheOdinProject/css-exercises#217] opened 2022-08-21 16:27 UTC
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by advaith017** [comment] 2022-10-20 15:08
Hey there, could you be more clear about which exercise has this issue? Thanks

**Comment by arinze19** [comment] 2023-02-10 05:12
This is probably relating to issue #259

**Comment by thatblindgeye** [comment] 2023-02-11 12:42
Closing as it is a duplicate of the above linked issue

**Closed by thatblindgeye** 2023-02-11 12:42 UTC
Labels: Type: Bug, Status: Invalid
