### ISSUE TITLE
Alignment: 07-flex-layout-2 missing CSS in the solutions

### ISSUE THREAD

**Issue by wishyrater** [TheOdinProject/css-exercises#539] opened 2024-05-01 22:43 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the task '07-flex-layout-2' the CSS solution details the following changes in order to fix the list-items in the sidebar:

`ul {
   list-style-type: none;
   margin: 0;
   padding: 0;
}`

However, this will not make the solution match the desired outcome, as the desired outcome has significantly more space between the link items.

To fix this, a few additional CSS properties need to be added:

`ul {
   list-style-type: none;
   margin: 0;
   padding: 0;
   display: flex;
   flex-direction: column;
   gap: 16px
}`

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-alignment

**Comment by MaoShizhong** [comment] 2024-05-01 23:09
Thanks for opening this issue @wishyrater, I've transferred this to the CSS exercises repo where the exercises are kept (and where any changes would need to be done if we need to do changes).

I've opened the solution HTML and CSS and compared that to the desired outcome images, as well as when the `ul` has the additional CSS properties as you've highlighted above.
You can see this comparison below.
Leftmost is with the additional flex properties, middle is the current solution CSS, and rightmost is the desired outcome image.

![image](https://github.com/TheOdinProject/css-exercises/assets/122839503/e960becd-f2fc-49c3-9228-80a179983c2c)

So based on that, we shouldn't need any additional CSS for the solution.

**Comment by MaoShizhong** [comment] 2024-05-03 15:39
Closing as cannot reproduce original issue.

**Closed by MaoShizhong** 2024-05-03 15:39 UTC
